package com.devson.vedinsta.repository

import android.content.Context
import android.util.Log
import java.io.File

object CookieFileWriter {
    private const val TAG = "CookieFileWriter"
    private const val COOKIE_FILE_NAME = "instagram_cookies.txt"

    /**
     * Writes the authentication cookies to a Netscape-format cookie file at the app's filesDir.
     * Netscape format: .instagram.com  TRUE  /  TRUE  <expiry_epoch>  <name>  <value>
     */
    fun writeCookies(
        context: Context,
        sessionId: String,
        csrfToken: String,
        dsUserId: String,
        otherCookies: Map<String, String> = emptyMap()
    ): Boolean {
        return try {
            val filesDir = context.filesDir
            val cookieFile = File(filesDir, COOKIE_FILE_NAME)
            
            val sb = StringBuilder()
            sb.append("# Netscape HTTP Cookie File\n")
            sb.append("# This file was generated by VedInsta\n\n")

            // Default expiry: 1 year from now (Epoch seconds)
            val expiryEpoch = (System.currentTimeMillis() / 1000) + (365 * 24 * 60 * 60)

            fun appendCookieLine(name: String, value: String) {
                // Netscape columns must be tab-separated
                sb.append(".instagram.com\tTRUE\t/\tTRUE\t$expiryEpoch\t$name\t$value\n")
            }

            appendCookieLine("sessionid", sessionId)
            appendCookieLine("csrftoken", csrfToken)
            appendCookieLine("ds_user_id", dsUserId)

            // Write all other optional cookies parsed from WebView
            for ((name, value) in otherCookies) {
                if (name != "sessionid" && name != "csrftoken" && name != "ds_user_id" && name.isNotBlank() && value.isNotBlank()) {
                    appendCookieLine(name, value)
                }
            }

            cookieFile.writeText(sb.toString())
            Log.d(TAG, "Successfully wrote Netscape cookies to: ${cookieFile.absolutePath}")
            true
        } catch (e: Exception) {
            Log.e(TAG, "Failed to write cookie file", e)
            false
        }
    }

    /**
     * Clears the cookies text file from filesDir.
     */
    fun clearCookies(context: Context): Boolean {
        return try {
            val cookieFile = File(context.filesDir, COOKIE_FILE_NAME)
            if (cookieFile.exists()) {
                val deleted = cookieFile.delete()
                Log.d(TAG, "Deleted cookie file: $deleted")
                deleted
            } else {
                true
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to delete cookie file", e)
            false
        }
    }
}
